In [1]:
import pandas as pd
import numpy as np

In [79]:
a = pd.read_csv("PRICELIST_17116.txt", delimiter=';', encoding='ANSI', names=['col_' + str(i) for i in range(9)])

In [75]:
a.dtypes

col_0      int64
col_1     object
col_2     object
col_3     object
col_4     object
col_5      int64
col_6     object
col_7     object
col_8    float64
dtype: object

In [38]:
a.dtypes.to_dict()

{'col_0': dtype('int64'),
 'col_1': dtype('O'),
 'col_2': dtype('O'),
 'col_3': dtype('O'),
 'col_4': dtype('O'),
 'col_5': dtype('int64'),
 'col_6': dtype('O'),
 'col_7': dtype('O'),
 'col_8': dtype('float64')}

In [80]:
for col in a.columns:
    a[col] = a[col].apply(str).apply(
            lambda x: "<NULL>" if x.isspace() else x.strip())

In [82]:
a = a.replace('<NULL>', '')

In [83]:
a

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8
0,6400024,,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H10 42W,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H10 42W,L,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,3.36
1,6400031,,7003.00239BL ΛΑΜΠΑ LED C5W T11 x 36 LED,7003.00239BL ΛΑΜΠΑ LED C5W T11 x 36 LED,R,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,8.04
2,6400032,,ΛΑΜΠΑ BLUE XENON H9 65W,ΛΑΜΠΑ BLUE XENON H9 65W,L,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,8.04
3,6400033,,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H9 65W,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H9 65W,R,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,3.36
4,6400043,,ΛΑΜΠΑ BLUE XENON H12 55W,ΛΑΜΠΑ BLUE XENON H12 55W,R,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,11.19
...,...,...,...,...,...,...,...,...,...
112797,895004281,7C0807178,ΒΑΣΗ ΠΡΟΦΥΛΑΚΤΗΡΑ ΕΜΠΡΟΣ ΠΛΑΙΝΗ ΠΛΑΣΤΙΚΗ,FRONT BUMPER SIDE BRACKET PLASTIC,R,8950,VW,VW CRAFTER 17-,7.67
112798,895004801,7C08079449B9,ΔΙΧΤΥ ΠΡΟΦΥΛ. ΕΜΠ.,FRONT BUMPER GRILLE,R,8950,VW,VW CRAFTER 17-,21.77
112799,895004802,7C08079439B9,ΔΙΧΤΥ ΠΡΟΦΥΛ. ΕΜΠ.,FRONT BUMPER GRILLE,L,8950,VW,VW CRAFTER 17-,21.77
112800,895004813,7C08072469B9,ΚΑΛΥΜΜΑ ΔΙΧΤΥΟΥ ΠΡΟΦΥΛΑΚΤΗΡΑ ΕΜΠΡΟΣ ΑΝΩ,FRONT BUMPER UPPER GRILLE COVER,R,8950,VW,VW CRAFTER 17-,10.46
112801,895006050,1K8943021,ΦΑΝΟΣ ΑΡΙΘΜΟΥ (Ε),LICENSE LAMP (E),,8950,VW,VW CRAFTER 17-,3.73

In [85]:
a.to_excel('change_col_val.xlsx', index=False)

In [44]:
df = pd.read_excel('test.xlsx')

In [74]:
df.loc[df['col_1'].isna()]

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8
0,6400024,NaN,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H10 42W,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H10 42W,L,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,3.36
1,6400031,NaN,7003.00239BL ΛΑΜΠΑ LED C5W T11 x 36 LED,7003.00239BL ΛΑΜΠΑ LED C5W T11 x 36 LED,R,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,8.04
2,6400032,NaN,ΛΑΜΠΑ BLUE XENON H9 65W,ΛΑΜΠΑ BLUE XENON H9 65W,L,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,8.04
3,6400033,NaN,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H9 65W,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H9 65W,R,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,3.36
4,6400043,NaN,ΛΑΜΠΑ BLUE XENON H12 55W,ΛΑΜΠΑ BLUE XENON H12 55W,R,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,11.19
...,...,...,...,...,...,...,...,...,...
112609,886008211,NaN,ΦΥΛΛΟ ΠΟΡΤΑΣ 5ης (ΔΙΠΛΗ) ΚΑΤΩ ΕΞΩ,TAIL GATE (TWIN) SKIN LOWER OUTER,R,8860,VW,VW TRANSPORTER (T4) 97-03,13.41
112610,886008212,NaN,ΦΥΛΛΟ ΠΟΡΤΑΣ 5ης (ΔΙΠΛΗ) ΚΑΤΩ ΕΞΩ,TAIL GATE (TWIN) SKIN LOWER OUTER,L,8860,VW,VW TRANSPORTER (T4) 97-03,13.41
112611,886008284,NaN,ΦΥΛΛΟ ΛΑΜΑΡΙΝΑ ΠΛΑΙΝΟΥ,SIDEWALL PANEL SKIN,L,8860,VW,VW TRANSPORTER (T4) 97-03,24.11
112687,890003645,NaN,ΠΡΟΦΥΛΑΚΤΗΡΑΣ ΠΙΣΩ ΒΑΦΟΜ. (ΜΕ PDS),REAR BUMPER PRIMED (W/PDS),NaN,8900,VW,VW GOLF VII 13-16,39.16
112750,892105130,NaN,ΦΑΝΟΣ ΕΜΠ.ΣΕΤ ΜΑΥΡΟΣ ΤΥΠΟΥ Α5,HEAD LAMP SET BLACK TYPE A5,NaN,8921,VW,VW GOLF VI VARIANT 09-14,324.52

In [72]:
df.isna().sum()

col_0        0
col_1    10709
col_2        9
col_3       29
col_4    41312
col_5        0
col_6        0
col_7        0
col_8        0
dtype: int64

In [17]:
df1 = pd.read_excel("GBG_DEIGMA_TELIKO-10000.xlsx")

In [23]:
df1.loc[df1['article_no_ΟΕΜ'].isna()]

Empty DataFrame
Columns: [brand, article_no_ΟΕΜ, retail_price, price_after_discount, car xml indicator, Γνήσιος κωδικός]
Index: []

In [112]:
for col in df1.columns:
    if df1[col].dtype == 'O':
        df1[col] = df1[col].str.strip()

In [5]:
def strip_whitespace(dataframe):
    for col in dataframe.columns:
        if dataframe[col].dtype == 'O':
            dataframe[col] = dataframe[col].str.strip()

In [11]:
strip_whitespace(df1)

In [19]:
def remove_overspace(text):
    return re.sub('\s{2,}', ' ', text).strip()

df1.isna().sum()

In [27]:
df1.loc[9994]['article_no_ΟΕΜ']

'16988500000000'

In [37]:
df1['article_no_ΟΕΜ'].str.replace(r'^\s*$', np.nan, regex=True)

TypeError: repl must be a string or callable

In [43]:
df1['article_no_ΟΕΜ'].apply(str)

0       72482-60A01
1       71711-60A40-5PK
2       72111-60A30
3       35300-60A31
4       82850-60A01
                ...
9994           16988500000000
9995    A1698205861
9996               1698201064
9997            8E0837462
9998    8E0941531A
Name: article_no_ΟΕΜ, Length: 9999, dtype: object

In [67]:
k = df1['article_no_ΟΕΜ'].apply(str).apply(lambda x: "<NULL>" if x.isspace() else x.strip())

In [68]:
mask = k == '<NULL>'

In [72]:
k[mask].replace('<NULL>', '')

90
458
459
461
468
       ..
9941
9942
9958
9989
9990
Name: article_no_ΟΕΜ, Length: 1127, dtype: object

In [57]:
df1.loc[df1['article_no_ΟΕΜ'].apply(str).str.isspace()]

,brand,article_no_ΟΕΜ,retail_price,price_after_discount,car xml indicator,Γνήσιος κωδικός
90,NaN,,46.264400,35.58800,1,10607140
458,NaN,,336.330904,258.71608,1,11305910
459,NaN,,27.013896,20.77992,1,11306142
461,NaN,,75.219144,57.86088,1,10006112
468,NaN,,10.539256,8.10712,1,10107602
...,...,...,...,...,...,...
9941,NaN,,618.182656,475.52512,1,21205271
9942,NaN,,618.182656,475.52512,1,21205272
9958,NaN,,0.180544,0.13888,1,21705140
9989,NaN,,8.688680,6.68360,1,21807861
9990,NaN,,8.688680,6.68360,1,21807862

In [100]:
a = df1.loc[df1['article_no_ΟΕΜ'].notna()]
b = df1.loc[df1['article_no_ΟΕΜ'].isna()]

In [101]:
merged_df = pd.concat([a, b], ignore_index=True)

In [102]:
merged_df.loc[merged_df['article_no_ΟΕΜ'].isna()]

,brand,article_no_ΟΕΜ,retail_price,price_after_discount,car xml indicator,Γνήσιος κωδικός
6432,NaN,NaN,162.218784,124.78368,1,10100812
6433,NaN,NaN,717.346448,551.80496,1,10101432
6434,NaN,NaN,31.098704,23.92208,1,10104540
6435,NaN,NaN,54.230904,41.71608,1,10106552
6436,NaN,NaN,31.369520,24.13040,1,10107100
...,...,...,...,...,...,...
9994,NaN,NaN,21.010808,16.16216,1,21006141
9995,NaN,NaN,21.010808,16.16216,1,21006142
9996,NaN,NaN,23.132200,17.79400,1,21107871
9997,NaN,NaN,144.435200,111.10400,1,21205134
9998,NaN,NaN,46.354672,35.65744,1,21905816

In [106]:
df = pd.read_excel("vals.xlsx", dtype='string')

In [107]:
for col in df.columns:
    if col == 'col_2':
        df[col] = df[col].apply(lambda x: "<NULL>" if x.isspace() else x.strip())
    else:
        df[col] = df[col].apply(lambda x: "" if x.isspace() else x.strip())

In [108]:
df['retail_price'] = (((df['col_9'].astype(float) * 1.24) * 1.3) * 1.30).round(2)

In [109]:
df['price_after_discount_30%'] = ((df['col_9'].astype(float) * 1.24) * 1.3).round(2)

In [110]:
df['car'] = 1

In [99]:
df

,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,retail_price,price_after_discount_30%,car
0,006400024,,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H10 42W,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H10 42W,L,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,3.36,7.04,5.42,1
1,006400031,,7003.00239BL ΛΑΜΠΑ LED C5W T11 x 36 LED,7003.00239BL ΛΑΜΠΑ LED C5W T11 x 36 LED,R,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,8.04,16.85,12.96,1
2,006400032,,ΛΑΜΠΑ BLUE XENON H9 65W,ΛΑΜΠΑ BLUE XENON H9 65W,L,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,8.04,16.85,12.96,1
3,006400033,,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H9 65W,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H9 65W,R,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,3.36,7.04,5.42,1
4,006400043,,ΛΑΜΠΑ BLUE XENON H12 55W,ΛΑΜΠΑ BLUE XENON H12 55W,R,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,11.19,23.45,18.04,1
...,...,...,...,...,...,...,...,...,...,...,...,...
112797,895004281,7C0807178,ΒΑΣΗ ΠΡΟΦΥΛΑΚΤΗΡΑ ΕΜΠΡΟΣ ΠΛΑΙΝΗ ΠΛΑΣΤΙΚΗ,FRONT BUMPER SIDE BRACKET PLASTIC,R,8950,VW,VW CRAFTER 17-,7.67,16.07,12.36,1
112798,895004801,7C08079449B9,ΔΙΧΤΥ ΠΡΟΦΥΛ. ΕΜΠ.,FRONT BUMPER GRILLE,R,8950,VW,VW CRAFTER 17-,21.77,45.62,35.09,1
112799,895004802,7C08079439B9,ΔΙΧΤΥ ΠΡΟΦΥΛ. ΕΜΠ.,FRONT BUMPER GRILLE,L,8950,VW,VW CRAFTER 17-,21.77,45.62,35.09,1
112800,895004813,7C08072469B9,ΚΑΛΥΜΜΑ ΔΙΧΤΥΟΥ ΠΡΟΦΥΛΑΚΤΗΡΑ ΕΜΠΡΟΣ ΑΝΩ,FRONT BUMPER UPPER GRILLE COVER,R,8950,VW,VW CRAFTER 17-,10.46,21.92,16.86,1
112801,895006050,1K8943021,ΦΑΝΟΣ ΑΡΙΘΜΟΥ (Ε),LICENSE LAMP (E),,8950,VW,VW CRAFTER 17-,3.73,7.82,6.01,1

In [111]:
df.loc[df['col_3'].str.contains("ΛΑΜΠΑ|ΜΑΡΣΠΙΕ|ΛΑΜΠΕΣ", regex=True, na=False), 'car'] = 0

In [112]:
df.insert(0, 'brand', '')

In [113]:
a = df.rename(columns={'col_1': 'Γνήσιος Κωδικός', 'car': 'car xml indicator'})

In [68]:
a.columns

Index(['brand', 'Γνήσιος Κωδικός', 'col_2', 'col_3', 'col_4', 'col_5', 'col_6',
       'col_7', 'col_8', 'col_9', 'retail_price', 'price_after_discount_30%',
       'car xml indicator'],
      dtype='object')

In [114]:
b = a[['brand', 'col_2', 'col_3', 'col_4', 'col_5', 'col_6', 'col_7', 'col_8', 'col_9','retail_price', 'price_after_discount_30%', 'car xml indicator', 'Γνήσιος Κωδικός']]

In [115]:
b

,brand,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,retail_price,price_after_discount_30%,car xml indicator,Γνήσιος Κωδικός
0,,<NULL>,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H10 42W,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H10 42W,L,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,3.36,7.04,5.42,0,006400024
1,,<NULL>,7003.00239BL ΛΑΜΠΑ LED C5W T11 x 36 LED,7003.00239BL ΛΑΜΠΑ LED C5W T11 x 36 LED,R,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,8.04,16.85,12.96,0,006400031
2,,<NULL>,ΛΑΜΠΑ BLUE XENON H9 65W,ΛΑΜΠΑ BLUE XENON H9 65W,L,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,8.04,16.85,12.96,0,006400032
3,,<NULL>,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H9 65W,ΛΑΜΠΑ ΑΛΟΓΟΝΟΥ H9 65W,R,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,3.36,7.04,5.42,0,006400033
4,,<NULL>,ΛΑΜΠΑ BLUE XENON H12 55W,ΛΑΜΠΑ BLUE XENON H12 55W,R,64,ΛΑΜΠΕΣ,ΛΑΜΠΕΣ / BULBS / XENON,11.19,23.45,18.04,0,006400043
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112797,,7C0807178,ΒΑΣΗ ΠΡΟΦΥΛΑΚΤΗΡΑ ΕΜΠΡΟΣ ΠΛΑΙΝΗ ΠΛΑΣΤΙΚΗ,FRONT BUMPER SIDE BRACKET PLASTIC,R,8950,VW,VW CRAFTER 17-,7.67,16.07,12.36,1,895004281
112798,,7C08079449B9,ΔΙΧΤΥ ΠΡΟΦΥΛ. ΕΜΠ.,FRONT BUMPER GRILLE,R,8950,VW,VW CRAFTER 17-,21.77,45.62,35.09,1,895004801
112799,,7C08079439B9,ΔΙΧΤΥ ΠΡΟΦΥΛ. ΕΜΠ.,FRONT BUMPER GRILLE,L,8950,VW,VW CRAFTER 17-,21.77,45.62,35.09,1,895004802
112800,,7C08072469B9,ΚΑΛΥΜΜΑ ΔΙΧΤΥΟΥ ΠΡΟΦΥΛΑΚΤΗΡΑ ΕΜΠΡΟΣ ΑΝΩ,FRONT BUMPER UPPER GRILLE COVER,R,8950,VW,VW CRAFTER 17-,10.46,21.92,16.86,1,895004813
112801,,1K8943021,ΦΑΝΟΣ ΑΡΙΘΜΟΥ (Ε),LICENSE LAMP (E),,8950,VW,VW CRAFTER 17-,3.73,7.82,6.01,1,895006050

In [72]:
b = b.replace('<NULL>', '')

In [116]:
ds = []

for i in range(11):
    start = 10000 * i
    end = 10000 * (i+1) if i<10 else df.shape[0]
    exp = b.iloc[start:end].copy()
    
    mask = exp['col_2'] == '<NULL>'

    c = exp.loc[~mask].copy()
    d = exp.loc[mask].copy()

    merged_df = pd.concat([c, d], ignore_index=True)
    merged_df['col_2'] = merged_df['col_2'].replace('<NULL>', '')
    
    merged_df.to_excel(f"files\\sample_{start}-{end}.xlsx", index=False)